### ISSUE TITLE
Using DEV at other deep domain adaptation models

### ISSUE THREAD

**Issue by userb2020** [youkaichao/Deep-Embedded-Validation#2]
Hello!
I am really interested in your work,
and I want to use your validation methods in my domain adaptation model.
And I have several questions when I am using the function get_weight in dev.py

The three input parameters (source_feature, target_feature, validation_feature) should be calculated using whole dataset or per batch?

And if I calculate it per batch, what is the right size of the batch?

It would be very thankful if you answer my questions.

**Comment by youkaichao** [comment]
Thanks for your interest.

It should be calculated using the whole dataset.

If the dataset is too large, you should perhaps implement a mini-batch version yourself.
